[workspace]
members = [
    "zomes/request",
    "zomes/contacts",
    "zomes/username",
    "zomes/p2pmessage",
    "zomes/p2pmessageasync"
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
