version: 2.1

# Define the jobs  we want to run for this project
jobs:
  build-and-test:
    docker:
      - image: guillemcordoba/rsm:latest
    steps:
      - checkout
      - run:
          name: "pull-submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: build-holochain
          working_directory: ~/project/dnas/lobby
          command: | 
            CARGO_TARGET_DIR=target cargo build --release --target wasm32-unknown-unknown
            dna-util -c kizuna.dna.workdir/
      - run:
          name: test-holochain
          working_directory: ~/project/dnas/lobby/tests
          command: |
            NODE_ENV=development npm install
            npm test

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build-and-test
