[package]
name = "request"
version = "0.0.1"
authors = [ "nkgardose" ]
edition = "2018"

[lib]
name = "request"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
serde = "=1.0.104"
hdk3 = { git = "https://github.com/holochain/holochain.git", branch = "call" }
derive_more = "0.99.9"